<h1>Emp</h1>

<table border="1">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Surname</td>
        <td>EnName</td>
        <td>EnSurname</td>
        <td>Nickname</td>
        <td>StartWork</td>
        <td>StartEmployee</td>
        <td>Department</td>
        <td>Team</td>
        <td>Position</td>
        <td>Birthday</td>
        <td>EmpNumbeId</td>
        <td>BankId</td>
        <td>BankName</td>
        <td>Tel.Number</td>
        <td>Address</td>
        <td>CurrentAddress</td>
        <td>Email</td>
        <td>CompanyEmail</td>
        <td>EmpType</td>
        <td>Salary</td>
        <td>Other</td>

    </tr>
    @foreach ($employees as $employee)
    <tr>
        <td>{{$employee['emp_id']}}</td>
        <td>{{$employee['emp_name']}}</td>
        <td>{{$employee['emp_surname']}}</td>
        <td>{{$employee['emp_en_name']}}</td>
        <td>{{$employee['emp_en_surname']}}</td>
        <td>{{$employee['emp_nickname']}}</td>
        <td>{{$employee['emp_start_work']}}</td>
        <td>{{$employee['emp_start_emp']}}</td>
        <td>{{$employee['de_id']}}</td>
        <td>{{$employee['team_id']}}</td>
        <td>{{$employee['pos_id']}}</td>
        <td>{{$employee['emp_birthday']}}</td>
        <td>{{$employee['emp_numberID']}}</td>
        <td>{{$employee['emp_bankID']}}</td>
        <td>{{$employee['bank_id']}}</td>
        <td>{{$employee['emp_phone']}}</td>
        <td>{{$employee['emp_address']}}</td>
        <td>{{$employee['current_address']}}</td>
        <td>{{$employee['emp_e_mail']}}</td>
        <td>{{$employee['emp_comp_e_mail']}}</td>
        <td>{{$employee['type_emp_id']}}</td>
        <td>{{$employee['salary']}}</td>
        <td>{{$employee['other']}}</td>
    </tr>
    @endforeach
</table>
